version: '3'
services:
  service:
    image: '${APP_NAME}:v${APP_VERSION}'
    volumes: 
      - "./:/usr/app"
    depends_on: 
      - mongodb
    build: .
    environment: 
      CONFIG_DB_URI: mongodb://mongodb:27017
    networks:
      - oas-test-net
  mongodb:
    image: mongo:4.2
    logging:
      driver: none
    networks:
      - oas-test-net
networks: 
  oas-test-net:
