version: '3'
services:
  service:
    image: '${APP_NAME}:v${APP_VERSION}'
    volumes: 
      - "./:/app"
    depends_on: 
      - mongodb
    build: .
    networks:
      - oas-test-net
  mongodb:
    image: mongo:4.2
    ports:
      - "27017"
    logging:
      driver: none
    networks:
      - oas-test-net
networks: 
  oas-test-net:
